name: brb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.4.2
  - autopep8=1.5.3
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - click=7.1.2
  - isort=4.3.21
  - lazy-object-proxy=1.4.3
  - libedit=3.1.20191231
  - libffi=3.3
  - mccabe=0.6.1
  - mkl=2020.1
  - ncurses=6.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - pandas=1.0.5
  - pip=20.1.1
  - pycodestyle=2.6.0
  - pylint=2.5.3
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - rope=0.17.0
  - scipy=1.5.0
  - setuptools=49.2.0
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - toml=0.10.1
  - wheel=0.34.2
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
prefix: /home/bruno/miniconda3/envs/brb
